language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
licenses:
  - android-sdk-license-.+
  - '.+'
sudo: false
jdk: oraclejdk8
notifications:
  email: false
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script: ./gradlew clean build jacocoDebugReport jacocoReleaseReport --continue --stacktrace
after_success:
- pip install --user codecov
- codecov
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
