language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
sudo: false
jdk: oraclejdk8
licenses:
- android-sdk-license-.+
- android-sdk-license-c81a61d9
notifications:
  email: false
script: ./gradlew clean build --continue --stacktrace
after_success:
- pip install --user codecov
- codecov
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
